# Generated by Django 4.2.3 on 2023-11-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSocio', models.CharField(max_length=80)),
                ('fechaIncorporacion', models.DateField()),
                ('anioNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
