# Generated by Django 4.2.3 on 2023-11-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='anioNacimiento',
            field=models.DateField(verbose_name='Año nacimiento'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='correoElectronico',
            field=models.EmailField(max_length=254, verbose_name='Corredo electronico'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='fechaIncorporacion',
            field=models.DateField(verbose_name='Fecha incorporacion'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='nombreSocio',
            field=models.CharField(max_length=80, verbose_name='Nombre socio'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='sexo',
            field=models.CharField(max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Numero de telefono'),
        ),
    ]
